
pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building'
            }
        }
        stage('Deploy - master') {
            when { branch "master" }
            steps {
                sh '''
                    fab -f /www/site/com.zqw2/my_deploy/fabfile.py deploy_group_lab:xts,vpc_lab,master
                '''
            }
        }

    }

    post {
        always {
            echo 'I have finished'
            emailext(
                subject: '${ENV, var="JOB_NAME"}-第${BUILD_NUMBER}次构建日志',
                body: '${FILE,path="jenkins/email-template.html"}',
                to: 'zhaoqiangwei20022@163.com,1339472610@qq.com,33048544@qq.com'
            )
        }
        success {
            echo 'I succeeeded!'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'I failed :('
        }
        changed {
            echo 'Things were different before...'
        }
    }
}

